### ISSUE TITLE
[Migrated #96] "Typical" measurement

### ISSUE THREAD

**Issue by kassemmkk** [chipfoundry/cace#19]
<details>
<summary>Original Issue Information</summary>

- Original issue: #96 in efabless/cace
- Created by: mole99
- Created at: 2024-08-14T06:53:16Z
- URL: https://github.com/efabless/cace/issues/96
</details>

From Tim:

The "typical" measurement is defined as the single measurement done at all "typical" conditions, where a "typical" condition is given, and otherwise the average over conditions, if a "typical" condition is not given.

Enumerating over, say, ss, sf, tt, fs, ff, then tt is clearly the typical condition and should be used in calculating the typical value, but it won't be if you use "enumerate".

The following should be valid:

```
conditions:
   corner:
      enumerate: [ss, sf, tt, fs, ff]
      typical: tt
```
