### ISSUE TITLE
"Typical" measurement

### ISSUE THREAD

**Issue by kassemmkk** [chipfoundry/cace#23]
_Originally created by @mole99 on 2024-08-14T06:53:16Z_

From Tim:

The "typical" measurement is defined as the single measurement done at all "typical" conditions, where a "typical" condition is given, and otherwise the average over conditions, if a "typical" condition is not given.

Enumerating over, say, ss, sf, tt, fs, ff, then tt is clearly the typical condition and should be used in calculating the typical value, but it won't be if you use "enumerate".

The following should be valid:

```
conditions:
   corner:
      enumerate: [ss, sf, tt, fs, ff]
      typical: tt
```
